### ISSUE TITLE
hove tooltip show time is too small, need an option

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#17]

**Comment by halfbrained** [comment]
Increasing delay would not be a good experience, since it usually pops up by accident :)

It now hides if mouse is not over dialog **and** if mouse moved some distance from original position.

So if you are hovering intentionally and mouse doesn't move - it will stay up. I think this works quite nice now

**Comment by Alexey-T** [comment]
maybe add additional timer-- start it in on_mouse_stop, and if timer passed--- show the form. if not passed and mouse moved-- dont show. it  will give good XP

**Comment by halfbrained** [comment]
Are asking to delay hover dialog beyond what `on_mouse_stop()` waits and server response delay? Because that is a terrible idea :)

For now I added a check and don't show dialog if cursor moved from `on_mouse_stop()` position (if this is what you asking - Ta-Da). Please see how that works for you.

**Comment by Alexey-T** [comment]
works good.
