### ISSUE TITLE
maybe disable autocomplete in strings/comments?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_lsp#28]
on this line

            msg_status(msg + _('Text is already formatted'))

after "Te" i got completion "Telegram/        .... text"

**Comment by halfbrained** [comment]
I don't think that is necessary, since it is requested by the user, and I get string token kind (Editor.get_token(TOKEN_GET_KIND...) in f-string expressions, so it will be disabled there as well.

Also I can't reproduce what you are describing
```
name = 0
print(f'na {na}')
```
After first `na` I get no completion, after second - proper `name`

**Comment by Alexey-T** [comment]
ok.
